const ADD_ANSWER = "ADD_ANSWER",
    REMOVE_ANSWER = "REMOVE_ANSWER",
    ADD_QUESTION = "ADD_QUESTION",
    REMOVE_QUESTION = "REMOVE_QUESTION",
    GET_USERS = "GET_USERS",
    GET_QUESTIONS = "GET_QUESTIONS",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT";